service: tyler

custom:
  serverless-offline:
    port: 3000

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline
  - serverless-offline-direct-lambda

functions:
  myLambda:
    handler: handler.hello
  hasRoute:
    handler: handler.hasRoute
    events:
      - http:
          path: /
          method: get
